# SPDX-FileCopyrightText: None
#
# SPDX-License-Identifier: CC0-1.0

theme = "congo"
baseURL = "https://sorairolake.github.io/"
defaultContentLanguage = "ja"

[outputs]
home = ["HTML", "JSON", "RSS"]
