languageCode = "ja"
languageName = "日本語"
title = "SorairoLake's Home Page"
copyright = """\
  &copy; 2021&ndash;2023 Shun Sakai \
  &middot; \
  [CC BY-ND 4.0](https://creativecommons.org/licenses/by-nd/4.0/deed.ja)\
  """

[params]
dateFormat = "2006-01-02"
description = "SorairoLakeのホームページ。"

[author]
name = "Shun Sakai"
image = "image/profile.png"
headline = "A programmer from Nagano, Japan."
links = [
  { github = "https://github.com/sorairolake" },
  { gitlab = "https://gitlab.com/sorairolake" },
  { twitter = "https://twitter.com/sorairolake" },
  { mastodon = "https://misskey.io/@sorairolake" },
]
