# SPDX-FileCopyrightText: None
#
# SPDX-License-Identifier: CC0-1.0

languageCode = "ja"
languageName = "日本語"
title = "SorairoLake's Home Page"
copyright = """\
  &copy; 2021&ndash;2024 Shun Sakai \
  &middot; \
  [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/deed.ja)\
  """

[params]
dateFormat = "2006-01-02"
description = "SorairoLakeのホームページ。"

[params.author]
name = "Shun Sakai"
image = "images/profile.png"
headline = "A programmer from Nagano, Japan."
links = [
  { x-twitter = "https://twitter.com/sorairolake" },
  { mastodon = "https://misskey.io/@sorairolake" },
  { github = "https://github.com/sorairolake" },
  { gitlab = "https://gitlab.com/sorairolake" },
]
