# SPDX-FileCopyrightText: 2022 Shun Sakai
#
# SPDX-License-Identifier: CC0-1.0

[[main]]
name = "私について"
pageRef = "about"
weight = 10

[[main]]
name = "プロジェクト"
pageRef = "projects"
weight = 20

[[main]]
name = "連絡先"
pageRef = "contact"
weight = 30

[[main]]
name = "リンク"
pageRef = "links"
weight = 40

[[main]]
name = "ブログ"
url = "https://sorairolake.github.io/blog/"
weight = 50

[[main]]
name = "このウェブサイトについて"
pageRef = "about-website"
weight = 60
