# SPDX-FileCopyrightText: None
#
# SPDX-License-Identifier: CC0-1.0

colorScheme = "ocean"

[footer]
showAppearanceSwitcher = true

[homepage]
layout = "profile"

[article]
showDate = false
showAuthor = false
showPagination = false
showReadingTime = false
showTableOfContents = true
