# SPDX-FileCopyrightText: 2022 Shun Sakai
#
# SPDX-License-Identifier: CC0-1.0

colorScheme = "blowfish"
enableSearch = true

[footer]
showAppearanceSwitcher = true

[homepage]
layout = "profile"

[article]
showAuthor = false
showPagination = false
showReadingTime = false
showTableOfContents = true

[list]
showSummary = true
