name: Deployment

on:
  push:
    branches:
      - develop
    tags:
      - 'v[0-9][0-9][0-9][0-9].[0-1][0-9].[0-3][0-9]'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: true
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2.6.0
      with:
        hugo-version: '0.115.2'
    - name: Build a website
      run: hugo --minify
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3.9.3
      if: startsWith(github.ref, 'refs/tags/')
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
