name: Deployment

on:
  push:
    branches:
      - 'master'
      - 'develop'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: true
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2.6.0
      with:
        hugo-version: 0.106.0
    - name: Build a website
      run: hugo --minify
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3.9.0
      if: ${{ github.ref == 'refs/heads/master' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
