# SPDX-FileCopyrightText: None
#
# SPDX-License-Identifier: CC0-1.0

name: Deployment

on:
  pull_request:
  push:
    branches:
      - "develop"
    tags:
      - "v[0-9][0-9][0-9][0-9].[0-1][0-9].[0-3][0-9]-?*"

permissions:
  contents: write

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Go environment
        uses: actions/setup-go@v5
        with:
          go-version: "stable"
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3.0.0
        with:
          hugo-version: "0.126.1"
          extended: true
      - name: Build a website
        run: hugo --minify
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4.0.0
        if: startsWith(github.ref, 'refs/tags/')
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
