# SPDX-FileCopyrightText: 2026 Shun Sakai
#
# SPDX-License-Identifier: CC0-1.0

name: rumdl

on:
  pull_request:
  push:
    branches:
      - "develop"
      - "main"
  workflow_dispatch:

jobs:
  rumdl:
    name: rumdl
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.3
      - name: Setup uv
        uses: astral-sh/setup-uv@v8.1.0
        with:
          enable-cache: true
      - name: Setup Python
        run: uv python install
      - name: Run rumdl
        run: uv run rumdl check --output-format full .
